### ISSUE TITLE
prompt toolkit changes break hdtv

### ISSUE THREAD

**Issue by warr** [janmayer/hdtv#35]
hdtv won't start. It gives the following traceback.

Traceback (most recent call last):
  File "/usr/bin/hdtv", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/hdtv/app.py", line 234, in run
    App()
  File "/usr/lib/python3.12/site-packages/hdtv/app.py", line 177, in __init__
    hdtv.cmdline.MainLoop()
  File "/usr/lib/python3.12/site-packages/hdtv/cmdline.py", line 720, in MainLoop
    line = self.session.prompt()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1035, in prompt
    return self.app.run(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/prompt_toolkit/application/application.py", line 961, in run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 661, in run_until_complete
    self._check_running()
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 620, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

The problem is introduced by commit:
https://github.com/janmayer/hdtv/commit/e1b49e3e8dcf4bb29a07d3e2ca09da7212c95c82

This is with prompt-toolkit 3.0.38.

**Comment by op3** [comment]
I can reproduce the problem for prompt_toolkit 3.0.38 and 3.0.39. Everything should work fine starting with prompt_toolkit 3.0.40.

Considering that [prompt_toolkit 3.0.40](https://github.com/prompt-toolkit/python-prompt-toolkit/releases/tag/3.0.40) was only released on 2023-11-10, we should also support older versions for now and handle both cases in the code.

**Comment by warr** [comment]
Yes, I can confirm that with Fedora 40 (beta version), which has 3.0.41, there is no problem. However, it will be a while before that gets through to the more conservative distributions. Fedora 39 still has 3.0.38.

**Comment by op3** [comment]
I pushed a fix that handles old versions of prompt_toolkit separately. I tested it with prompt_toolkit 3.0.40, 3.0.39, 3.0.38, 3.0.36, 3.0.27, and 3.0.14.
